### PR TITLE
Enabling net451

### PR DESCRIPTION
**Pull request by moozzyk**
Addresses #22

### CODE REVIEW

**Comment by davidfowl** [comment]
I want samples split. We're no longer multi targeting for applications by default, just libraries

**Comment by moozzyk** [comment]
I am not a big fun of duplicating the code if the only difference will be a handful lines in project.json files

**Comment by davidfowl** [comment]
We have to duplicate the code because I want this repository to reflect what real applications will look lile. I also want the differences in `project.json` to stand out.

**Pull request closed without merging**
