### PR TITLE
Unpinning Microsoft.Extensions.DependencyModel

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by pakrym** [comment]
@pranavkm are we building against the latest?

**Comment by pranavkm** [comment]
Yeah, we should be pulling in the newest on a nightly basis. We currently have `1.0.0-dev-001200`

**Comment by moozzyk** [comment]
Yes. I build both projects on my box after removing dependencies and they built and ran fine.

**Comment by pakrym** [comment]
:shipit:

**Pull request merged**
