### PR TITLE
Updating samples to use new publish-iis

### PR DESCRIPTION
**Pull request by moozzyk**
Removing web.config files since they are not needed - they will be created during publish

### CODE REVIEW

**Comment by moozzyk** [comment]
Published each project manually to verify that they work in IIS

**Comment by moozzyk** [comment]
@davidfowl - FYI you must be on the aspnetcirelease feed (aspnetcidev has old cli packages and IISIntegration doesn't even build ProjectContext.IsPortable is missing)

**Comment by davidfowl** [comment]
@moozzyk https://github.com/aspnet/cli-samples/blob/master/NuGet.Config#L5 done a while ago 😄

**Pull request merged**
